### ISSUE TITLE
database_cleaner undefined method

### ISSUE THREAD

**Issue by pglombardo** [andriusch/blueprints#6]
I just installed and configured blueprints into my rspec tests and upon running I receive the  stack trace below.

I'm not sure which gem is causing the error: blueprint or mysql2 (or me).  Any pointers to a resolution would be appreciated.

My environment is Rails 3, Linux.  

Here is my Gemfile:
    gem 'rails', '3.0.0'
    gem 'mysql2'

```
group :development, :test do
  gem "rspec-rails", ">= 2.0.1", :group => [:development, :test]
  gem "rspec"
  gem "rspec-core"
  gem "rspec-expectations"
  gem "rspec-mocks"
  gem "cucumber-rails"
  gem "capybara"
  gem "shoulda"
  gem "autotest"
  gem "blueprints"
 end

gem "devise"
gem "haml", ">= 3.0.0"
gem "haml-rails"
gem "hpricot"
gem "ruby_parser"
gem "aws-s3"
gem "will_paginate", ">= 3.0.pre"
```

And the stack trace:

```
  /usr/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib/database_cleaner/active_record/truncation.rb:77:in `clean': undefined method `truncate_table' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x7fd052f268c0> (NoMethodError)
from /usr/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib/database_cleaner/active_record/truncation.rb:76:in `each'
from /usr/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib/database_cleaner/active_record/truncation.rb:76:in `clean'
from /usr/lib/ruby/gems/1.8/gems/mysql2-0.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:232:in `disable_referential_integrity'
from /usr/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib/database_cleaner/active_record/truncation.rb:75:in `clean'
from /usr/lib/ruby/gems/1.8/gems/database_cleaner-0.5.2/lib/database_cleaner/configuration.rb:47:in `clean_with'
from /usr/lib/ruby/gems/1.8/gems/blueprints-0.8.2/lib/blueprints.rb:49:in `load'
from /usr/lib/ruby/gems/1.8/gems/blueprints-0.8.2/lib/blueprints.rb:91:in `if_orm'
from /usr/lib/ruby/gems/1.8/gems/blueprints-0.8.2/lib/blueprints.rb:48:in `load'
from /usr/lib/ruby/gems/1.8/gems/blueprints-0.8.2/lib/blueprints.rb:33:in `enable'
from /home/pglombardo/Projects/app1/spec/spec_helper.rb:6
from /home/pglombardo/Projects/app1/spec/controllers/admin_controller_spec.rb:1:in `require'
from /home/pglombardo/Projects/app1/spec/controllers/admin_controller_spec.rb:1
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `load'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `load_spec_files'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `map'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/configuration.rb:334:in `load_spec_files'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/command_line.rb:18:in `run'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:55:in `run_in_process'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:46:in `run'
from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.1.0/lib/rspec/core/runner.rb:10
from /usr/lib/ruby/gems/1.8/bin/rspec:19
```

rake aborted!

**Comment by andriusch** [comment]
This is basically due to blueprints depending on older version of database cleaner which does not support mysql2 yet. One workaround is use mysql gem for now, another is add this to your spec_helper, before blueprints is enabled:

```
module ActiveRecord
  module ConnectionAdapters
    class Mysql2Adapter < AbstractAdapter
      def truncate_table(table_name)
        execute("TRUNCATE TABLE #{quote_table_name(table_name)};")
      end
    end
  end
end
```

I'll update dependencies later today.

**Comment by andriusch** [comment]
So it appears that I can't really update dependency due to bug in database cleaner. For now please use the workaround above. This will be fixed once https://github.com/bmabey/database_cleaner/issues#issue/23 is fixed

**Comment by pglombardo** [comment]
The work-around you posted works flawlessly.  Thanks a million.
